eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 9001
spring:
  application:
    name: zuul
zuul:
  routes:
#  http://localhost:9001/order/test/testListProducts 替换成 http://localhost:7001/test/testListProducts
#    myorder:
#     path: /myorder/**
#     serviceId: order
#      开启cookie，如果不设置，zuul不支持cookie设置和传递
#      sensitiveHeaders:
#     简写
     order: /myorder/**
     product: /myproduct/**
#     排除不需要暴露的接口
#  ignored-patterns:
#    - /**/test/testListProducts

#解决这个超时问题 ： com.netflix.zuul.exception.ZuulException: Hystrix Readed time out
  host:
   connect-timeout-millis: 10000
   socket-timeout-millis: 60000

#management:
#  security:
#    enabled: false

#加上这个解决偶尔超时问题
hystrix:
  command:
   default:
    execution:
     isolation:
       thread:
        timeoutInMilliseconds: 6000
#解决这个超时问题 ： com.netflix.zuul.exception.ZuulException: Hystrix Readed time out
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000

