eureka:
  client:
    service-url:
     defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: product
spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/o2o?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
  jpa:
    show-sql: true





