eureka:
  client:
   service-url:
     defaultZone: http://localhost:8761/eureka/
   registery-fetch-interval-seconds: 2
   eureka-server-connect-timeout-seconds: 20
   eureka-server-read-timeout-seconds: 10
   filter-only-up-instances: true
  instance:
   lease-expiration-duration-in-seconds: 2
   lease-renewal-interval-in-seconds: 2
#   以上配置说明  https://www.cnblogs.com/hfultrastrong/p/8623288.html    Spring Cloud Eureka 常用配置及说明  →  https://www.cnblogs.com/li3807/p/7282492.html
#       lease-renewal-interval-in-seconds 每间隔1s，向服务端发送一次心跳，证明自己依然”存活“
#   　lease-expiration-duration-in-seconds  告诉服务端，如果我2s之内没有给你发心跳，就代表我“死”了，将我踢出掉。
#  instance:
#    hostname: order
spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/o2o?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
  jpa:
    show-sql: true
#  设置超时时间否则调用product会超时报错：→  feign.RetryableException: Read timed out executing POST http://product/product/listForOrder
ribbon:
  ReadTimeout: 60000
  ConnectionTimeout: 60000




