eureka:
  client:
    service-url:
     defaultZone: http://localhost:8761/eureka/
    registery-fetch-interval-seconds: 2
    eureka-server-connect-timeout-seconds: 20
    eureka-server-read-timeout-seconds: 10
    filter-only-up-instances: true
#  instance:
#    hostname: product        Spring Cloud Eureka 常用配置及说明  →  https://www.cnblogs.com/li3807/p/7282492.html
spring:
  application:
    name: product
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/o2o?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
  jpa:
    show-sql: true
server:
  port: 8082




